In [3]:
print("hello2")

hello2

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
#Read File
#data_url="https://storage.googleapis.com/covid19-open-data/v3/epidemiology.csv"
df_path="/Users/Alia Nouman/Downloads/epidemiology.csv"
covid_df=pd.read_csv(df_path)

In [11]:
covid_df.head()

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
0,2020-01-01,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
1,2020-01-02,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
2,2020-01-03,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
3,2020-01-04,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
4,2020-01-05,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN

In [34]:
#Inspecting the dataframe
# covid_df.shape #Shape of the objects(rows and Columns)
# covid_df.dtypes  #Data types in each column
covid_df.columns  #Column names

# covid_df.head()  #Display  first 5 rows
# covid_df.tail()  #Display last 5 rows
# covid_df.sample() #Display random 5 rows
# covid_df.info() #DataFrame information
# covid_df.describe()

Index(['date', 'location_key', 'new_confirmed', 'new_deceased',
       'new_recovered', 'new_tested', 'cumulative_confirmed',
       'cumulative_deceased', 'cumulative_recovered', 'cumulative_tested'],
      dtype='object')

In [ ]:
#Subsetting a dataframe-by rows and columns(also cover multiple condition-AND,OR)
denmark_covid_off=covid_df[covid_df['location_key']=="DK"]
india_covid_off=covid_df[covid_df['location_key']=="IN"]
covid_df.shape  
#shape is number for rows and columns
print("Denmark",denmark_covid_off.shape)
print("India",india_covid_off.shape)

Denmark (987, 10)
India (987, 10)

In [ ]:
#dk_in_covid_df=covid_df[(covid_df['location_key']=="DK") & (covid_df['location_key']=="IN")]
dk_in_covid_df=covid_df[(covid_df['location_key']=="DK" )| (covid_df['location_key']=="IN")]
dk_in_covid_df.shape
print("Denmark & India",dk_in_covid_df.shape)

Denmark & India (1974, 10)

In [59]:
#Assignment- Section A
# 1. What is the number of unique values in the column "location_key"?
unique_values_df=covid_df['location_key'].nunique()
print(unique_values_df)

20905

In [ ]:
# 2. What's the earliest date for which the data has been collected for? And the latest date? 
covid_df['date'] = pd.to_datetime(covid_df['date'])
earliest_date = covid_df['date'].min()
latest_date = covid_df['date'].max()
print("Earliest Date:", earliest_date)
print("Latest Date:", latest_date)

Earliest Date: 2019-12-31 00:00:00
Latest Date: 2022-12-30 00:00:00

In [62]:
# 3. On how many dates did we see the reported deaths greater than 100? 
deceased_100= covid_df[covid_df['new_deceased']>100]
ndates_df=deceased_100['date'].nunique()
print(ndates_df)

#len(covid_df[covid_df['new_deceased']>100])

937

In [ ]:
# Section B
# 1. All the data for the year 2021 only.
dates_2021_df=covid_df[covid_df['date']=="2021"]
print("Dates ",dates_2021_df.shape)

Dates  (14709, 10)

In [63]:
# 2. Denmark, but only the data from 2020. 
data_2020_df=covid_df[(covid_df['date']=="2020") & (covid_df['location_key']=="DK" )]
print("Dates ", data_2020_df)

Dates                date location_key  new_confirmed  new_deceased  new_recovered  \
6585013 2020-01-01           DK            0.0           0.0            NaN

         new_tested  cumulative_confirmed  cumulative_deceased  \
6585013         NaN                   0.0                  0.0

         cumulative_recovered  cumulative_tested
6585013                   NaN                NaN

In [ ]:
# 3. India, but also all the dates where the new cases reported were more than 1000. 
subset_india_df = covid_df[(covid_df['location_key'] == 'India') & (covid_df['new_confirmed'] >= 1000)]
print(subset_india_df.shape)

(0, 10)

In [67]:
# leaner_df=covid_df["date","location_key","new_confirmed", "new_deceased", "new_recovered", "new_tested"]
# print(leaner_df)

In [ ]:
# Section D
# subset_new_recovered=covid_df['new_recovered'].nunique()
# print(subset_new_recovered)

subset_new_recovered=covid_df['new_recovered'].nunique()
print(subset_new_recovered)

20709

In [ ]:
covid_df['date'] = pd.to_datetime(covid_df['date'])

# 1. Subset for all data from the year 2022
subset_2022 = covid_df[covid_df['date'].dt.year == 2022]

In [58]:
#new confirmed cases
subset_new_confirmed=covid_df['new_confirmed'].nunique()
print(subset_new_confirmed)

26183

In [ ]:

# ind_df=dk_in_covid_df[dk_in_covid_df['location_key']=="IN"]
# ind_df['date'] = pd.to_datetime(ind_df['date'])
# ind_df['DayOfWeek']= ind_df['date'].dt.day_of_week

# mean_dayofweek_df = ind_df.groupby(['DayOfWeek'])['new_tested'].mean()

C:\Users\Alia Nouman\AppData\Local\Temp\ipykernel_25076\3009599426.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ind_df['date'] = pd.to_datetime(ind_df['date'])
C:\Users\Alia Nouman\AppData\Local\Temp\ipykernel_25076\3009599426.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ind_df['DayOfWeek']= ind_df['date'].dt.day_of_week

In [77]:
#mortality rate
new_deceased=covid_df['new_deceased']
new_confirmed=covid_df['new_confirmed']
covid_df['mortality_rate']=new_deceased/new_confirmed
covid_df.shape
covid_df.sample()

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested,mortality_rate
1860018,2022-08-23,BR_MG_310540,0.0,0.0,NaN,NaN,7719.0,85.0,NaN,NaN,NaN